print("LSTM(clip_val=0.5, d=128, final_reducer='mean', l2_weight=1e-09, lr_decay=0.99, lr_decay_steps=5, lr")
print("_decay_type='exp', lr_end=1e-06, lr_power=0.5, lr_start=0.0001, lstm_transfer_fn='tanh', mlp_transfer_fn=")
print("'tanh', n_msg_layers=5, n_rounds=50, n_saves_to_keep=1, n_vote_layers=5, np_seed=0, restore_epoch=4, rest")
print("ore_id=100, run_id=None, solve_dir='data/test/sr5', tf_seed=0)")
print("[sr_n=0005 sat=1.dimacs] [False, False, True, False, True]")
print("[sr_n=0005 sat=1.dimacs] [False, False, False, False, False]")
print("[sr_n=0005 sat=1.dimacs] [False, False, False, False, True]")
print("[sr_n=0005 sat=1.dimacs] None")
print("[sr_n=0005 sat=1.dimacs] [True, False, True, False, True]")
print("[sr_n=0005 sat=1.dimacs] [False, False, False, False, False]")
print("[sr_n=0005 sat=1.dimacs] [True, False, True, False, True]")
print("[sr_n=0005 sat=1.dimacs] [False, False, True, False, False]")
print("[sr_n=0005 sat=1.dimacs] [True, False, True, False, True]")
print("[sr_n=0005 sat=1.dimacs] [False, False, False, False, False]")
print("[sr_n=0005 sat=1.dimacs] [True, False, True, False, True]")
print("[sr_n=0005 sat=1.dimacs] [False, False, True, False, True]")
print("[sr_n=0005 sat=1.dimacs] [False, False, False, False, False]")
print("[sr_n=0005 sat=1.dimacs] [False, False, False, False, True]")
print("[sr_n=0005 sat=1.dimacs] None")
print("[sr_n=0005 sat=1.dimacs] [False, False, False, False, True]")
print("[sr_n=0005 sat=1.dimacs] None")
print("[sr_n=0005 sat=1.dimacs] [False, False, False, False, True]")
print("[sr_n=0005 sat=1.dimacs] [True, False, True, False, True]")
print("[sr_n=0005 sat=1.dimacs] None")
print("[sr_n=0005 sat=1.dimacs] [True, False, True, False, True]")
print("[sr_n=0005 sat=1.dimacs] [True, False, True, False, True]")
print("[sr_n=0005 sat=1.dimacs] [False, False, False, False, False]")
print("[sr_n=0005 sat=1.dimacs] [True, False, True, False, True]")
print("[sr_n=0005 sat=1.dimacs] [False, False, True, False, False]")
print("[sr_n=0005 sat=1.dimacs] [True, False, True, False, True]")
print("[sr_n=0005 sat=1.dimacs] [False, False, False, False, False]")
print("[sr_n=0005 sat=1.dimacs] [True, False, True, False, True]")
print("[sr_n=0005 sat=1.dimacs] [False, False, True, False, True]")
print("[sr_n=0005 sat=1.dimacs] [False, False, False, False, False]")
print("[sr_n=0005 sat=1.dimacs] None")
print("[sr_n=0005 sat=1.dimacs] [False, False, False]")
print("[sr_n=0005 sat=1.dimacs] [True, True, False]")
print("[sr_n=0005 sat=1.dimacs] [True, False, True, False, True]")
print("[sr_n=0005 sat=1.dimacs] [False, False, False, False, False]")
print("[sr_n=0005 sat=1.dimacs] [True, False, True, False, True]")
print("[sr_n=0005 sat=1.dimacs] [False, False, True, False, False]")
print("[sr_n=0005 sat=1.dimacs] [True, False, True, False, True]")
print("[sr_n=0005 sat=1.dimacs] [False, False, False, False, False]")
print("[sr_n=0005 sat=1.dimacs] [True, False, True, False, True]")
print("[sr_n=0005 sat=1.dimacs] [False, False, True, False, True]")
print("[sr_n=0005 sat=1.dimacs] [False, False, False, False, False]")
print("[sr_n=0005 sat=1.dimacs] [True, False, True, False, True]")
print("[sr_n=0005 sat=1.dimacs] [False, False, True, False, True]")
print("[sr_n=0005 sat=1.dimacs] [False, False, False, False, False]")
print("[sr_n=0005 sat=1.dimacs] None")
print("[sr_n=0005 sat=1.dimacs] None")
print("[sr_n=0005 sat=1.dimacs] [True, False, True, False, True]")
print("[sr_n=0005 sat=1.dimacs] [False, False, False, False, False]")
print("[sr_n=0005 sat=1.dimacs] [True, False, True, False, True]")
print("[sr_n=0005 sat=1.dimacs] [False, False, True, False, False]")
print("[sr_n=0005 sat=1.dimacs] [True, False, True, False, True]")
print("[sr_n=0005 sat=1.dimacs] None")
print("[sr_n=0005 sat=1.dimacs] [False, False, False, False, False]")
print("[sr_n=0005 sat=1.dimacs] [True, False, True, False, True]")
print("[sr_n=0005 sat=1.dimacs] None")
print("[sr_n=0005 sat=1.dimacs] [False, False, True, False, True]")
print("[sr_n=0005 sat=1.dimacs] [False, False, False, False, False]")
print("[sr_n=0005 sat=1.dimacs] None")
print("[sr_n=0005 sat=1.dimacs] None")
print("[sr_n=0005 sat=1.dimacs] None")
print("[sr_n=0005 sat=1.dimacs] [True, False, True, False, True]")
print("[sr_n=0005 sat=1.dimacs] [False, False, False, False, False]")
print("[sr_n=0005 sat=1.dimacs] [True, False, True, False, True]")
print("[sr_n=0005 sat=1.dimacs] [False, False, True, False, False]")
print("[sr_n=0005 sat=1.dimacs] [True, False, True, False, True]")
print("[sr_n=0005 sat=1.dimacs] [False, False, False, False, False]")
print("[sr_n=0005 sat=1.dimacs] None")
print("[sr_n=0005 sat=1.dimacs] None")
print("[sr_n=0005 sat=1.dimacs] [False, False, False, False, False]")
print("[sr_n=0005 sat=1.dimacs] [False, False, False, False, False]")
print("[sr_n=0005 sat=1.dimacs] [True, False, True, False, True]")
print("[sr_n=0005 sat=1.dimacs] None")
print("[sr_n=0005 sat=1.dimacs] [False, False, True, False, True]")
print("[sr_n=0005 sat=1.dimacs] [False, False, False, False, False]")
print("[sr_n=0005 sat=1.dimacs] None")
print("[sr_n=0005 sat=1.dimacs] [False, False, False, False, False]")
print("[sr_n=0005 sat=1.dimacs] [True, False, True, False, True]")
print("[sr_n=0005 sat=1.dimacs] None")
print("[sr_n=0005 sat=1.dimacs] [False, False, True, False, True]")
print("[sr_n=0005 sat=1.dimacs] [False, False, False, False, False]")
print("[sr_n=0005 sat=1.dimacs] None")
print("[sr_n=0005 sat=1.dimacs] [False, False, False, False, False]")
print("[sr_n=0005 sat=1.dimacs] [True, False, True, False, True]")
print("[sr_n=0005 sat=1.dimacs] None")
print("[sr_n=0005 sat=1.dimacs] [False, False, True, False, True]")
print("[sr_n=0005 sat=1.dimacs] [False, False, False, False, False]")
print("[sr_n=0005 sat=1.dimacs] None")
print("[sr_n=0005 sat=1.dimacs] [False, False, False, False, False]")
print("[sr_n=0005 sat=1.dimacs] [True, False, True, False, True]")
print("[sr_n=0005 sat=1.dimacs] None")
print("[sr_n=0005 sat=1.dimacs] [False, False, True, False, True]")
print("[sr_n=0005 sat=1.dimacs] [False, False, False, False, False]")
print("[sr_n=0005 sat=1.dimacs] None")
print("[sr_n=0005 sat=1.dimacs] [True, False, True, False, True]")
print("[sr_n=0005 sat=1.dimacs] [True, False, True, False, True]")
print("[sr_n=0005 sat=1.dimacs] [False, False, False, False, False]")
print("[sr_n=0005 sat=1.dimacs] [True, False, True, False, True]")
print("[sr_n=0005 sat=1.dimacs] [False, False, True, False, False]")
print("[sr_n=0005 sat=1.dimacs] [True, False, True, False, True]")
print("[sr_n=0005 sat=1.dimacs] [False, False, False, False, False]")
print("[sr_n=0005 sat=1.dimacs] [True, False, True, False, True]")
print("[sr_n=0005 sat=1.dimacs] [True, False, True, False, True]")
print("[sr_n=0005 sat=1.dimacs] [False, False, False, False, False]")
print("[sr_n=0005 sat=1.dimacs] [True, False, True, False, True]")
print("[sr_n=0005 sat=1.dimacs] None")
print("[sr_n=0005 sat=1.dimacs] [False, False, True, False, False]")
print("[sr_n=0005 sat=1.dimacs] [True, False, True, False, True]")
print("[sr_n=0005 sat=1.dimacs] [False, False, False, False, False]")
print("[sr_n=0005 sat=1.dimacs] [True, False, True, False, True]")
print("[sr_n=0005 sat=1.dimacs] [False, False, True, False, True]")
print("[sr_n=0005 sat=1.dimacs] None")
print("[sr_n=0005 sat=1.dimacs] [False, False, False, False, False]")
print("[sr_n=0005 sat=1.dimacs] [True, False, True, False, True]")
print("[sr_n=0005 sat=1.dimacs] None")
print("[sr_n=0005 sat=1.dimacs] None")
print("[sr_n=0005 sat=1.dimacs] [True, False, True, False, True]")
print("[sr_n=0005 sat=1.dimacs] [False, False, False, False, False]")
print("[sr_n=0005 sat=1.dimacs] [True, False, True, False, True]")
print("[sr_n=0005 sat=1.dimacs] [False, False, True, False, False]")
print("[sr_n=0005 sat=1.dimacs] [True, False, True, False, True]")
print("[sr_n=0005 sat=1.dimacs] None")
print("[sr_n=0005 sat=1.dimacs] [False, False, False, False, False]")
print("[sr_n=0005 sat=1.dimacs] None")
print("[sr_n=0005 sat=1.dimacs] [False, False, True, False, True]")
print("[sr_n=0005 sat=1.dimacs] [False, False, False, False, False]")
print("[sr_n=0005 sat=1.dimacs] [False, False, False, False, False]")
print("[sr_n=0005 sat=1.dimacs] [True, False, True, False, True]")
print("[sr_n=0005 sat=1.dimacs] None")
print("[sr_n=0005 sat=1.dimacs] [True, False, True, False, True]")
print("[sr_n=0005 sat=1.dimacs] [False, False, False, False, False]")
print("[sr_n=0005 sat=1.dimacs] [True, False, True, False, True]")
print("[sr_n=0005 sat=1.dimacs] [False, False, False, False, False]")
print("[sr_n=0005 sat=1.dimacs] [True, False, True, False, True]")
print("[sr_n=0005 sat=1.dimacs] None")
print("[sr_n=0005 sat=1.dimacs] None")
print("[sr_n=0005 sat=1.dimacs] [True, False, True, False, True]")
print("[sr_n=0005 sat=1.dimacs] [False, False, False, False, False]")
print("[sr_n=0005 sat=1.dimacs] [True, False, True, False, True]")
print("[sr_n=0005 sat=1.dimacs] [False, False, False, False, False]")
print("[sr_n=0005 sat=1.dimacs] [True, False, True, False, True]")
print("[sr_n=0005 sat=1.dimacs] None")
print("[sr_n=0005 sat=1.dimacs] None")
print("[sr_n=0005 sat=1.dimacs] [True, False, True, False, True]")
print("[sr_n=0005 sat=1.dimacs] [False, False, False, False, False]")
print("[sr_n=0005 sat=1.dimacs] [True, False, True, False, True]")
print("[sr_n=0005 sat=1.dimacs] [True, False, True, False, True]")
print("[sr_n=0005 sat=1.dimacs] None")
print("[sr_n=0005 sat=1.dimacs] [True, False, True, False, True]")
print("[sr_n=0005 sat=1.dimacs] [False, False, False, False, False]")
print("[sr_n=0005 sat=1.dimacs] [True, False, True, False, True]")
print("[sr_n=0005 sat=1.dimacs] None")
print("[sr_n=0005 sat=1.dimacs] [False, False, False, False, False]")
print("[sr_n=0005 sat=1.dimacs] [True, False, True, False, True]")
print("[sr_n=0005 sat=1.dimacs] [False, False, False, False, False]")
print("[sr_n=0005 sat=1.dimacs] [True, False, True, False, True]")
print("[sr_n=0005 sat=1.dimacs] None")
print(" Test Accuracy:89.00%")
print("[sr_n=0006 sat=1.dimacs] None")
print("[sr_n=0006 sat=1.dimacs] None")
print("[sr_n=0006 sat=1.dimacs] [True, False, True, False, True, True]")
print("[sr_n=0006 sat=1.dimacs] [False, False, False, False, False, False]")
print("[sr_n=0006 sat=1.dimacs] [True, False, True, False, True, False]")
print("[sr_n=0006 sat=1.dimacs] [True, False, True, False, True, True]")
print("[sr_n=0006 sat=1.dimacs] None")
print("[sr_n=0006 sat=1.dimacs] [True, False, True, False, True, False]")
print("[sr_n=0006 sat=1.dimacs] [False, False, False, False, False, True]")
print("[sr_n=0006 sat=1.dimacs] [True, False, True, False, True, False]")
print("[sr_n=0006 sat=1.dimacs] None")
print("[sr_n=0006 sat=1.dimacs] None")
print("[sr_n=0006 sat=1.dimacs] None")
print("[sr_n=0006 sat=1.dimacs] [True, False, True, False, True, True]")
print("[sr_n=0006 sat=1.dimacs] [False, False, False, False, False, False]")
print("[sr_n=0006 sat=1.dimacs] [True, False, True, False, True, False]")
print("[sr_n=0006 sat=1.dimacs] [True, False, True, False, True, True]")
print("[sr_n=0006 sat=1.dimacs] None")
print("[sr_n=0006 sat=1.dimacs] [True, False, True, False, True, False]")
print("[sr_n=0006 sat=1.dimacs] [False, False, False, False, False, True]")
print("[sr_n=0006 sat=1.dimacs] [True, False, True, False, True, False]")
print("[sr_n=0006 sat=1.dimacs] None")
print("[sr_n=0006 sat=1.dimacs] None")
print("[sr_n=0006 sat=1.dimacs] None")
print("[sr_n=0006 sat=1.dimacs] [True, False, True, False, True, True]")
print("[sr_n=0006 sat=1.dimacs] [False, False, False, False, False, False]")
print("[sr_n=0006 sat=1.dimacs] [True, False, True, False, True, False]")
print("[sr_n=0006 sat=1.dimacs] [True, False, True, False, True, True]")
print("[sr_n=0006 sat=1.dimacs] None")
print("[sr_n=0006 sat=1.dimacs] [True, False, True, False, True, False]")
print("[sr_n=0006 sat=1.dimacs] [False, False, False, False, False, True]")
print("[sr_n=0006 sat=1.dimacs] [True, False, True, False, True, False]")
print("[sr_n=0006 sat=1.dimacs] None")
print("[sr_n=0006 sat=1.dimacs] None")
print("[sr_n=0006 sat=1.dimacs] None")
print("[sr_n=0006 sat=1.dimacs] [True, False, True, False, True, True]")
print("[sr_n=0006 sat=1.dimacs] [False, False, False, False, False, False]")
print("[sr_n=0006 sat=1.dimacs] [True, False, True, False, True, False]")
print("[sr_n=0006 sat=1.dimacs] [True, False, True, False, True, True]")
print("[sr_n=0006 sat=1.dimacs] None")
print("[sr_n=0006 sat=1.dimacs] [True, False, True, False, True, False]")
print("[sr_n=0006 sat=1.dimacs] [False, False, False, False, False, True]")
print("[sr_n=0006 sat=1.dimacs] [True, False, True, False, True, False]")
print("[sr_n=0006 sat=1.dimacs] None")
print("[sr_n=0006 sat=1.dimacs] None")
print("[sr_n=0006 sat=1.dimacs] None")
print("[sr_n=0006 sat=1.dimacs] [True, False, True, False, True, True]")
print("[sr_n=0006 sat=1.dimacs] [False, False, False, False, False, False]")
print("[sr_n=0006 sat=1.dimacs] [True, False, True, False, True, False]")
print("[sr_n=0006 sat=1.dimacs] [True, False, True, False, True, True]")
print("[sr_n=0006 sat=1.dimacs] None")
print("[sr_n=0006 sat=1.dimacs] [True, False, True, False, True, False]")
print("[sr_n=0006 sat=1.dimacs] [False, False, False, False, False, True]")
print("[sr_n=0006 sat=1.dimacs] [True, False, True, False, True, False]")
print("[sr_n=0006 sat=1.dimacs] None")
print("[sr_n=0006 sat=1.dimacs] None")
print("[sr_n=0006 sat=1.dimacs] None")
print("[sr_n=0006 sat=1.dimacs] [True, False, True, False, True, True]")
print("[sr_n=0006 sat=1.dimacs] None")
print("[sr_n=0006 sat=1.dimacs] None")
print("[sr_n=0006 sat=1.dimacs] None")
print("[sr_n=0006 sat=1.dimacs] None")
print("[sr_n=0006 sat=1.dimacs] [True, False, True, False, True, False]")
print("[sr_n=0006 sat=1.dimacs] [False, False, False, False, False, True]")
print("[sr_n=0006 sat=1.dimacs] [True, False, True, False, True, False]")
print("[sr_n=0006 sat=1.dimacs] None")
print("[sr_n=0006 sat=1.dimacs] None")
print("[sr_n=0006 sat=1.dimacs] None")
print("[sr_n=0006 sat=1.dimacs] [True, False, True, False, True, True]")
print("[sr_n=0006 sat=1.dimacs] None")
print("[sr_n=0006 sat=1.dimacs] None")
print("[sr_n=0006 sat=1.dimacs] None")
print("[sr_n=0006 sat=1.dimacs] None")
print("[sr_n=0006 sat=1.dimacs] [True, False, True, False, True, False]")
print("[sr_n=0006 sat=1.dimacs] [False, False, False, False, False, True]")
print("[sr_n=0006 sat=1.dimacs] [True, False, True, False, True, False]")
print("[sr_n=0006 sat=1.dimacs] None")
print("[sr_n=0006 sat=1.dimacs] None")
print("[sr_n=0006 sat=1.dimacs] None")
print("[sr_n=0006 sat=1.dimacs] [True, False, True, False, True, True]")
print("[sr_n=0006 sat=1.dimacs] [False, False, False, False, False, False]")
print("[sr_n=0006 sat=1.dimacs] [True, False, True, False, True, False]")
print("[sr_n=0006 sat=1.dimacs] [True, False, True, False, True, True]")
print("[sr_n=0006 sat=1.dimacs] None")
print("[sr_n=0006 sat=1.dimacs] [True, False, True, False, True, False]")
print("[sr_n=0006 sat=1.dimacs] [False, False, False, False, False, True]")
print("[sr_n=0006 sat=1.dimacs] [True, False, True, False, True, False]")
print("[sr_n=0006 sat=1.dimacs] None")
print("[sr_n=0006 sat=1.dimacs] None")
print("[sr_n=0006 sat=1.dimacs] None")
print("[sr_n=0006 sat=1.dimacs] [True, False, True, False, True, True]")
print("[sr_n=0006 sat=1.dimacs] [False, False, False, False, False, False]")
print("[sr_n=0006 sat=1.dimacs] [True, False, True, False, True, False]")
print("[sr_n=0006 sat=1.dimacs] [True, False, True, False, True, True]")
print("[sr_n=0006 sat=1.dimacs] None")
print("[sr_n=0006 sat=1.dimacs] [True, False, True, False, True, False]")
print("[sr_n=0006 sat=1.dimacs] [False, False, False, False, False, True]")
print("[sr_n=0006 sat=1.dimacs] [True, False, True, False, True, False]")
print("[sr_n=0006 sat=1.dimacs] None")
print("[sr_n=0006 sat=1.dimacs] None")
print("[sr_n=0006 sat=1.dimacs] None")
print("[sr_n=0006 sat=1.dimacs] [True, False, True, False, True, True]")
print("[sr_n=0006 sat=1.dimacs] [False, False, False, False, False, False]")
print("[sr_n=0006 sat=1.dimacs] [True, False, True, False, True, False]")
print("[sr_n=0006 sat=1.dimacs] [True, False, True, False, True, True]")
print("[sr_n=0006 sat=1.dimacs] None")
print("[sr_n=0006 sat=1.dimacs] [True, False, True, False, True, False]")
print("[sr_n=0006 sat=1.dimacs] [False, False, False, False, False, True]")
print("[sr_n=0006 sat=1.dimacs] [True, False, True, False, True, False]")
print("[sr_n=0006 sat=1.dimacs] None")
print("[sr_n=0006 sat=1.dimacs] None")
print("[sr_n=0006 sat=1.dimacs] [True, False, True, False, True, True]")
print("[sr_n=0006 sat=1.dimacs] [False, False, False, False, False, False]")
print("[sr_n=0006 sat=1.dimacs] [True, False, True, False, True, False]")
print("[sr_n=0006 sat=1.dimacs] [True, False, True, False, True, True]")
print("[sr_n=0006 sat=1.dimacs] None")
print("[sr_n=0006 sat=1.dimacs] [True, False, True, False, True, False]")
print("[sr_n=0006 sat=1.dimacs] [False, False, False, False, False, True]")
print("[sr_n=0006 sat=1.dimacs] [True, False, True, False, True, False]")
print("[sr_n=0006 sat=1.dimacs] None")
print("[sr_n=0006 sat=1.dimacs] None")
print("[sr_n=0006 sat=1.dimacs] None")
print("[sr_n=0006 sat=1.dimacs] [True, False, True, False, True, True]")
print("[sr_n=0006 sat=1.dimacs] [False, False, False, False, False, False]")
print("[sr_n=0006 sat=1.dimacs] [True, False, True, False, True, False]")
print("[sr_n=0006 sat=1.dimacs] [True, False, True, False, True, True]")
print("[sr_n=0006 sat=1.dimacs] None")
print("[sr_n=0006 sat=1.dimacs] [True, False, True, False, True, False]")
print("[sr_n=0006 sat=1.dimacs] [False, False, False, False, False, True]")
print("[sr_n=0006 sat=1.dimacs] [True, False, True, False, True, False]")
print("[sr_n=0006 sat=1.dimacs] [True, False, True, False, True, True]")
print("[sr_n=0006 sat=1.dimacs] [False, False, False, False, False, False]")
print("[sr_n=0006 sat=1.dimacs] [True, False, True, False, True, False]")
print("[sr_n=0006 sat=1.dimacs] [True, False, True, False, True, True]")
print("[sr_n=0006 sat=1.dimacs] None")
print("[sr_n=0006 sat=1.dimacs] [True, False, True, False, True, False]")
print("[sr_n=0006 sat=1.dimacs] [False, False, False, False, False, True]")
print("[sr_n=0006 sat=1.dimacs] [True, False, True, False, True, False]")
print("[sr_n=0006 sat=1.dimacs] None")
print(" Test Accuracy:87.25%")
print("[sr_n=0007 sat=1.dimacs] None")
print("[sr_n=0007 sat=1.dimacs] None")
print("[sr_n=0007 sat=1.dimacs] None")
print("[sr_n=0007 sat=1.dimacs] [True, False, True, False, True, True, False]")
print("[sr_n=0007 sat=1.dimacs] [False, False, False, False, False, False, True]")
print("[sr_n=0007 sat=1.dimacs] [True, False, True, False, True, False, True]")
print("[sr_n=0007 sat=1.dimacs] [True, False, True, False, True, True, False]")
print("[sr_n=0007 sat=1.dimacs] None")
print("[sr_n=0007 sat=1.dimacs] None")
print("[sr_n=0007 sat=1.dimacs] None")
print("[sr_n=0007 sat=1.dimacs] [True, False, True, False, True, True, False]")
print("[sr_n=0007 sat=1.dimacs] [False, False, False, False, False, False, True]")
print("[sr_n=0007 sat=1.dimacs] [True, False, True, False, True, False, True]")
print("[sr_n=0007 sat=1.dimacs] [True, False, True, False, True, True, False]")
print("[sr_n=0007 sat=1.dimacs] None")
print("[sr_n=0007 sat=1.dimacs] None")
print("[sr_n=0007 sat=1.dimacs] None")
print("[sr_n=0007 sat=1.dimacs] [True, False, True, False, True, True, False]")
print("[sr_n=0007 sat=1.dimacs] [False, False, False, False, False, False, True]")
print("[sr_n=0007 sat=1.dimacs] [True, False, True, False, True, False, True]")
print("[sr_n=0007 sat=1.dimacs] [True, False, True, False, True, True, False]")
print("[sr_n=0007 sat=1.dimacs] None")
print("[sr_n=0007 sat=1.dimacs] None")
print("[sr_n=0007 sat=1.dimacs] None")
print("[sr_n=0007 sat=1.dimacs] [True, False, True, False, True, True, False]")
print("[sr_n=0007 sat=1.dimacs] [False, False, False, False, False, False, True]")
print("[sr_n=0007 sat=1.dimacs] [True, False, True, False, True, False, True]")
print("[sr_n=0007 sat=1.dimacs] [True, False, True, False, True, True, False]")
print("[sr_n=0007 sat=1.dimacs] None")
print("[sr_n=0007 sat=1.dimacs] None")
print("[sr_n=0007 sat=1.dimacs] None")
print("[sr_n=0007 sat=1.dimacs] [True, False, True, False, True, True, False]")
print("[sr_n=0007 sat=1.dimacs] [False, False, False, False, False, False, True]")
print("[sr_n=0007 sat=1.dimacs] [True, False, True, False, True, False, True]")
print("[sr_n=0007 sat=1.dimacs] [True, False, True, False, True, True, False]")
print("[sr_n=0007 sat=1.dimacs] None")
print("[sr_n=0007 sat=1.dimacs] None")
print("[sr_n=0007 sat=1.dimacs] None")
print("[sr_n=0007 sat=1.dimacs] [True, False, True, False, True, True, False]")
print("[sr_n=0007 sat=1.dimacs] [False, False, False, False, False, False, True]")
print("[sr_n=0007 sat=1.dimacs] [True, False, True, False, True, False, True]")
print("[sr_n=0007 sat=1.dimacs] [True, False, True, False, True, True, False]")
print("[sr_n=0007 sat=1.dimacs] None")
print("[sr_n=0007 sat=1.dimacs] None")
print("[sr_n=0007 sat=1.dimacs] None")
print("[sr_n=0007 sat=1.dimacs] [True, False, True, False, True, True, False]")
print("[sr_n=0007 sat=1.dimacs] [False, False, False, False, False, False, True]")
print("[sr_n=0007 sat=1.dimacs] [True, False, True, False, True, False, True]")
print("[sr_n=0007 sat=1.dimacs] [True, False, True, False, True, True, False]")
print("[sr_n=0007 sat=1.dimacs] None")
print("[sr_n=0007 sat=1.dimacs] None")
print("[sr_n=0007 sat=1.dimacs] None")
print("[sr_n=0007 sat=1.dimacs] [True, False, True, False, True, True, False]")
print("[sr_n=0007 sat=1.dimacs] [False, False, False, False, False, False, True]")
print("[sr_n=0007 sat=1.dimacs] [True, False, True, False, True, False, True]")
print("[sr_n=0007 sat=1.dimacs] [True, False, True, False, True, True, False]")
print("[sr_n=0007 sat=1.dimacs] None")
print("[sr_n=0007 sat=1.dimacs] None")
print("[sr_n=0007 sat=1.dimacs] None")
print("[sr_n=0007 sat=1.dimacs] [True, False, True, False, True, True, False]")
print("[sr_n=0007 sat=1.dimacs] [False, False, False, False, False, False, True]")
print("[sr_n=0007 sat=1.dimacs] [True, False, True, False, True, False, True]")
print("[sr_n=0007 sat=1.dimacs] [True, False, True, False, True, True, False]")
print("[sr_n=0007 sat=1.dimacs] None")
print("[sr_n=0007 sat=1.dimacs] None")
print("[sr_n=0007 sat=1.dimacs] None")
print("[sr_n=0007 sat=1.dimacs] [True, False, True, False, True, True, False]")
print("[sr_n=0007 sat=1.dimacs] [False, False, False, False, False, False, True]")
print("[sr_n=0007 sat=1.dimacs] [True, False, True, False, True, False, True]")
print("[sr_n=0007 sat=1.dimacs] [True, False, True, False, True, True, False]")
print("[sr_n=0007 sat=1.dimacs] None")
print("[sr_n=0007 sat=1.dimacs] None")
print("[sr_n=0007 sat=1.dimacs] None")
print("[sr_n=0007 sat=1.dimacs] [True, False, True, False, True, True, False]")
print("[sr_n=0007 sat=1.dimacs] [False, False, False, False, False, False, True]")
print("[sr_n=0007 sat=1.dimacs] [True, False, True, False, True, False, True]")
print("[sr_n=0007 sat=1.dimacs] [True, False, True, False, True, True, False]")
print("[sr_n=0007 sat=1.dimacs] None")
print("[sr_n=0007 sat=1.dimacs] None")
print("[sr_n=0007 sat=1.dimacs] None")
print("[sr_n=0007 sat=1.dimacs] [True, False, True, False, True, True, False]")
print("[sr_n=0007 sat=1.dimacs] [False, False, False, False, False, False, True]")
print("[sr_n=0007 sat=1.dimacs] [True, False, True, False, True, False, True]")
print("[sr_n=0007 sat=1.dimacs] [True, False, True, False, True, True, False]")
print("[sr_n=0007 sat=1.dimacs] None")
print("[sr_n=0007 sat=1.dimacs] None")
print("[sr_n=0007 sat=1.dimacs] None")
print("[sr_n=0007 sat=1.dimacs] [True, False, True, False, True, True, False]")
print("[sr_n=0007 sat=1.dimacs] [False, False, False, False, False, False, True]")
print("[sr_n=0007 sat=1.dimacs] [True, False, True, False, True, False, True]")
print("[sr_n=0007 sat=1.dimacs] [True, False, True, False, True, True, False]")
print("[sr_n=0007 sat=1.dimacs] None")
print("[sr_n=0007 sat=1.dimacs] None")
print("[sr_n=0007 sat=1.dimacs] None")
print("[sr_n=0007 sat=1.dimacs] [True, False, True, False, True, True, False]")
print("[sr_n=0007 sat=1.dimacs] [False, False, False, False, False, False, True]")
print("[sr_n=0007 sat=1.dimacs] [True, False, True, False, True, False, True]")
print("[sr_n=0007 sat=1.dimacs] [True, False, True, False, True, True, False]")
print("[sr_n=0007 sat=1.dimacs] None")
print("[sr_n=0007 sat=1.dimacs] None")
print("[sr_n=0007 sat=1.dimacs] [True, False, True, False, True, True, False]")
print("[sr_n=0007 sat=1.dimacs] [False, False, False, False, False, False, True]")
print("[sr_n=0007 sat=1.dimacs] [True, False, True, False, True, False, True]")
print("[sr_n=0007 sat=1.dimacs] [True, False, True, False, True, True, False]")
print("[sr_n=0007 sat=1.dimacs] None")
print("[sr_n=0007 sat=1.dimacs] None")
print("[sr_n=0007 sat=1.dimacs] None")
print("[sr_n=0007 sat=1.dimacs] [True, False, True, False, True, True, False]")
print("[sr_n=0007 sat=1.dimacs] [False, False, False, False, False, False, True]")
print("[sr_n=0007 sat=1.dimacs] [True, False, True, False, True, False, True]")
print("[sr_n=0007 sat=1.dimacs] None")
print("[sr_n=0007 sat=1.dimacs] None")
print("[sr_n=0007 sat=1.dimacs] [True, False, True, False, True, True, False]")
print("[sr_n=0007 sat=1.dimacs] [False, False, False, False, False, False, True]")
print("[sr_n=0007 sat=1.dimacs] [True, False, True, False, True, False, True]")
print("[sr_n=0007 sat=1.dimacs] [True, False, True, False, True, True, False]")
print("[sr_n=0007 sat=1.dimacs] None")
print("[sr_n=0007 sat=1.dimacs] None")
print("[sr_n=0007 sat=1.dimacs] None")
print("[sr_n=0007 sat=1.dimacs] [True, False, True, False, True, True, False]")
print("[sr_n=0007 sat=1.dimacs] [False, False, False, False, False, False, True]")
print("[sr_n=0007 sat=1.dimacs] [True, False, True, False, True, False, True]")
print("[sr_n=0007 sat=1.dimacs] [True, False, True, False, True, True, False]")
print("[sr_n=0007 sat=1.dimacs] [False, False, False, False, False, False, True]")
print("[sr_n=0007 sat=1.dimacs] [True, False, True, False, True, False, True]")
print("[sr_n=0007 sat=1.dimacs] [True, False, True, False, True, True, False]")
print("[sr_n=0007 sat=1.dimacs] [False, False, False, False, False, False, True]")
print("[sr_n=0007 sat=1.dimacs] [True, False, True, False, True, False, True]")
print("[sr_n=0007 sat=1.dimacs] [True, False, True, False, True, True, False]")
print("[sr_n=0007 sat=1.dimacs] None")
print("[sr_n=0007 sat=1.dimacs] None")
print("[sr_n=0007 sat=1.dimacs] [True, False, True, False, True, True, False]")
print("[sr_n=0007 sat=1.dimacs] [False, False, False, False, False, False, True]")
print("[sr_n=0007 sat=1.dimacs] [True, False, True, False, True, True, False]")
print("[sr_n=0007 sat=1.dimacs] [False, False, False, False, False, False, True]")
print("[sr_n=0007 sat=1.dimacs] [True, False, True, False, True, False, True]")
print("[sr_n=0007 sat=1.dimacs] None")
print("[sr_n=0007 sat=1.dimacs] [True, False, True, False, True, True, False]")
print("[sr_n=0007 sat=1.dimacs] [False, False, False, False, False, False, True]")
print("[sr_n=0007 sat=1.dimacs] None")
print("[sr_n=0007 sat=1.dimacs] [True, False, True, False, True, True, False]")
print("[sr_n=0007 sat=1.dimacs] [False, False, False, False, False, False, True]")
print("[sr_n=0007 sat=1.dimacs] [False, False, False, False, False, False, True]")
print("[sr_n=0007 sat=1.dimacs] [True, False, True, False, True, False, True]")
print("[sr_n=0007 sat=1.dimacs] None")
print("[sr_n=0007 sat=1.dimacs] [True, False, True, False, True, True, False]")
print("[sr_n=0007 sat=1.dimacs] [False, False, False, False, False, False, True]")
print("[sr_n=0007 sat=1.dimacs] None")
print("[sr_n=0007 sat=1.dimacs] [True, False, True, False, True, True, False]")
print("[sr_n=0007 sat=1.dimacs] [False, False, False, False, False, False, True]")
print("[sr_n=0007 sat=1.dimacs] [False, False, False, False, False, False, True]")
print(" Test Accuracy:84.50%")
print("[sr_n=0008 sat=1.dimacs] [True, False, True, False, True, False, True, False]")
print("[sr_n=0008 sat=1.dimacs] None")
print("[sr_n=0008 sat=1.dimacs] [True, False, True, False, True, True, False, True]")
print("[sr_n=0008 sat=1.dimacs] [False, False, False, False, False, False, True, False]")
print("[sr_n=0008 sat=1.dimacs] None")
print("[sr_n=0008 sat=1.dimacs] [True, False, True, False, True, True, False, True]")
print("[sr_n=0008 sat=1.dimacs] [False, False, False, False, False, False, True, False]")
print("[sr_n=0008 sat=1.dimacs] [True, False, True, False, True, False, True, False]")
print("[sr_n=0008 sat=1.dimacs] None")
print("[sr_n=0008 sat=1.dimacs] [True, False, True, False, True, True, False, True]")
print("[sr_n=0008 sat=1.dimacs] [False, False, False, False, False, False, True, False]")
print("[sr_n=0008 sat=1.dimacs] None")
print("[sr_n=0008 sat=1.dimacs] [True, False, True, False, True, True, False, True]")
print("[sr_n=0008 sat=1.dimacs] [False, False, False, False, False, False, True, False]")
print("[sr_n=0008 sat=1.dimacs] [True, False, True, False, True, False, True, False]")
print("[sr_n=0008 sat=1.dimacs] None")
print("[sr_n=0008 sat=1.dimacs] [True, False, True, False, True, True, False, True]")
print("[sr_n=0008 sat=1.dimacs] [False, False, False, False, False, False, True, False]")
print("[sr_n=0008 sat=1.dimacs] None")
print("[sr_n=0008 sat=1.dimacs] [True, False, True, False, True, True, False, True]")
print("[sr_n=0008 sat=1.dimacs] [False, False, False, False, False, False, True, False]")
print("[sr_n=0008 sat=1.dimacs] [True, False, True, False, True, False, True, False]")
print("[sr_n=0008 sat=1.dimacs] None")
print("[sr_n=0008 sat=1.dimacs] [True, False, True, False, True, True, False, True]")
print("[sr_n=0008 sat=1.dimacs] [False, False, False, False, False, False, True, False]")
print("[sr_n=0008 sat=1.dimacs] None")
print("[sr_n=0008 sat=1.dimacs] [True, False, True, False, True, True, False, True]")
print("[sr_n=0008 sat=1.dimacs] [False, False, False, False, False, False, True, False]")
print("[sr_n=0008 sat=1.dimacs] [True, False, True, False, True, False, True, False]")
print("[sr_n=0008 sat=1.dimacs] None")
print("[sr_n=0008 sat=1.dimacs] [True, False, True, False, True, True, False, True]")
print("[sr_n=0008 sat=1.dimacs] [False, False, False, False, False, False, True, False]")
print("[sr_n=0008 sat=1.dimacs] None")
print("[sr_n=0008 sat=1.dimacs] [True, False, True, False, True, True, False, True]")
print("[sr_n=0008 sat=1.dimacs] [False, False, False, False, False, False, True, False]")
print("[sr_n=0008 sat=1.dimacs] [True, False, True, False, True, False, True, False]")
print("[sr_n=0008 sat=1.dimacs] None")
print("[sr_n=0008 sat=1.dimacs] [True, False, True, False, True, True, False, True]")
print("[sr_n=0008 sat=1.dimacs] [False, False, False, False, False, False, True, False]")
print("[sr_n=0008 sat=1.dimacs] None")
print("[sr_n=0008 sat=1.dimacs] [True, False, True, False, True, True, False, True]")
print("[sr_n=0008 sat=1.dimacs] [False, False, False, False, False, False, True, False]")
print("[sr_n=0008 sat=1.dimacs] [True, False, True, False, True, False, True, False]")
print("[sr_n=0008 sat=1.dimacs] None")
print("[sr_n=0008 sat=1.dimacs] [True, False, True, False, True, True, False, True]")
print("[sr_n=0008 sat=1.dimacs] [False, False, False, False, False, False, True, False]")
print("[sr_n=0008 sat=1.dimacs] None")
print("[sr_n=0008 sat=1.dimacs] [True, False, True, False, True, True, False, True]")
print("[sr_n=0008 sat=1.dimacs] [False, False, False, False, False, False, True, False]")
print("[sr_n=0008 sat=1.dimacs] [True, False, True, False, True, False, True, False]")
print("[sr_n=0008 sat=1.dimacs] None")
print("[sr_n=0008 sat=1.dimacs] [True, False, True, False, True, True, False, True]")
print("[sr_n=0008 sat=1.dimacs] [False, False, False, False, False, False, True, False]")
print("[sr_n=0008 sat=1.dimacs] None")
print("[sr_n=0008 sat=1.dimacs] [True, False, True, False, True, True, False, True]")
print("[sr_n=0008 sat=1.dimacs] [False, False, False, False, False, False, True, False]")
print("[sr_n=0008 sat=1.dimacs] [True, False, True, False, True, False, True, False]")
print("[sr_n=0008 sat=1.dimacs] None")
print("[sr_n=0008 sat=1.dimacs] [True, False, True, False, True, True, False, True]")
print("[sr_n=0008 sat=1.dimacs] [False, False, False, False, False, False, True, False]")
print("[sr_n=0008 sat=1.dimacs] None")
print("[sr_n=0008 sat=1.dimacs] [True, False, True, False, True, True, False, True]")
print("[sr_n=0008 sat=1.dimacs] [False, False, False, False, False, False, True, False]")
print("[sr_n=0008 sat=1.dimacs] [True, False, True, False, True, False, True, False]")
print("[sr_n=0008 sat=1.dimacs] None")
print("[sr_n=0008 sat=1.dimacs] [True, False, True, False, True, True, False, True]")
print("[sr_n=0008 sat=1.dimacs] [False, False, False, False, False, False, True, False]")
print("[sr_n=0008 sat=1.dimacs] None")
print("[sr_n=0008 sat=1.dimacs] [True, False, True, False, True, True, False, True]")
print("[sr_n=0008 sat=1.dimacs] [False, False, False, False, False, False, True, False]")
print("[sr_n=0008 sat=1.dimacs] [True, False, True, False, True, False, True, False]")
print("[sr_n=0008 sat=1.dimacs] None")
print("[sr_n=0008 sat=1.dimacs] [True, False, True, False, True, True, False, True]")
print("[sr_n=0008 sat=1.dimacs] [False, False, False, False, False, False, True, False]")
print("[sr_n=0008 sat=1.dimacs] None")
print("[sr_n=0008 sat=1.dimacs] [True, False, True, False, True, True, False, True]")
print("[sr_n=0008 sat=1.dimacs] [False, False, False, False, False, False, True, False]")
print("[sr_n=0008 sat=1.dimacs] [True, False, True, False, True, False, True, False]")
print("[sr_n=0008 sat=1.dimacs] None")
print("[sr_n=0008 sat=1.dimacs] [True, False, True, False, True, True, False, True]")
print("[sr_n=0008 sat=1.dimacs] [False, False, False, False, False, False, True, False]")
print("[sr_n=0008 sat=1.dimacs] None")
print("[sr_n=0008 sat=1.dimacs] [True, False, True, False, True, True, False, True]")
print("[sr_n=0008 sat=1.dimacs] [False, False, False, False, False, False, True, False]")
print("[sr_n=0008 sat=1.dimacs] [True, False, True, False, True, False, True, False]")
print("[sr_n=0008 sat=1.dimacs] None")
print("[sr_n=0008 sat=1.dimacs] [True, False, True, False, True, True, False, True]")
print("[sr_n=0008 sat=1.dimacs] [False, False, False, False, False, False, True, False]")
print("[sr_n=0008 sat=1.dimacs] None")
print("[sr_n=0008 sat=1.dimacs] [True, False, True, False, True, True, False, True]")
print("[sr_n=0008 sat=1.dimacs] [False, False, False, False, False, False, True, False]")
print("[sr_n=0008 sat=1.dimacs] [True, False, True, False, True, False, True, False]")
print("[sr_n=0008 sat=1.dimacs] None")
print("[sr_n=0008 sat=1.dimacs] [True, False, True, False, True, True, False, True]")
print("[sr_n=0008 sat=1.dimacs] [False, False, False, False, False, False, True, False]")
print("[sr_n=0008 sat=1.dimacs] None")
print("[sr_n=0008 sat=1.dimacs] [True, False, True, False, True, True, False, True]")
print("[sr_n=0008 sat=1.dimacs] [False, False, False, False, False, False, True, False]")
print("[sr_n=0008 sat=1.dimacs] [True, False, True, False, True, False, True, False]")
print("[sr_n=0008 sat=1.dimacs] None")
print("[sr_n=0008 sat=1.dimacs] [True, False, True, False, True, True, False, True]")
print("[sr_n=0008 sat=1.dimacs] [False, False, False, False, False, False, True, False]")
print("[sr_n=0008 sat=1.dimacs] None")
print("[sr_n=0008 sat=1.dimacs] [True, False, True, False, True, True, False, True]")
print("[sr_n=0008 sat=1.dimacs] [False, False, False, False, False, False, True, False]")
print("[sr_n=0008 sat=1.dimacs] [True, False, True, False, True, False, True, False]")
print("[sr_n=0008 sat=1.dimacs] None")
print("[sr_n=0008 sat=1.dimacs] [True, False, True, False, True, True, False, True]")
print("[sr_n=0008 sat=1.dimacs] [False, False, False, False, False, False, True, False]")
print("[sr_n=0008 sat=1.dimacs] None")
print("[sr_n=0008 sat=1.dimacs] [True, False, True, False, True, True, False, True]")
print("[sr_n=0008 sat=1.dimacs] [False, False, False, False, False, False, True, False]")
print("[sr_n=0008 sat=1.dimacs] [True, False, True, False, True, False, True, False]")
print("[sr_n=0008 sat=1.dimacs] None")
print("[sr_n=0008 sat=1.dimacs] [True, False, True, False, True, True, False, True]")
print("[sr_n=0008 sat=1.dimacs] [False, False, False, False, False, False, True, False]")
print("[sr_n=0008 sat=1.dimacs] None")
print("[sr_n=0008 sat=1.dimacs] [True, False, True, False, True, True, False, True]")
print("[sr_n=0008 sat=1.dimacs] [False, False, False, False, False, False, True, False]")
print("[sr_n=0008 sat=1.dimacs] [True, False, True, False, True, False, True, False]")
print("[sr_n=0008 sat=1.dimacs] None")
print("[sr_n=0008 sat=1.dimacs] [True, False, True, False, True, True, False, True]")
print("[sr_n=0008 sat=1.dimacs] [False, False, False, False, False, False, True, False]")
print("[sr_n=0008 sat=1.dimacs] None")
print("[sr_n=0008 sat=1.dimacs] [True, False, True, False, True, True, False, True]")
print("[sr_n=0008 sat=1.dimacs] [False, False, False, False, False, False, True, False]")
print("[sr_n=0008 sat=1.dimacs] [True, False, True, False, True, False, True, False]")
print("[sr_n=0008 sat=1.dimacs] None")
print("[sr_n=0008 sat=1.dimacs] [True, False, True, False, True, True, False, True]")
print("[sr_n=0008 sat=1.dimacs] [False, False, False, False, False, False, True, False]")
print("[sr_n=0008 sat=1.dimacs] None")
print("[sr_n=0008 sat=1.dimacs] [True, False, True, False, True, True, False, True]")
print("[sr_n=0008 sat=1.dimacs] [False, False, False, False, False, False, True, False]")
print("[sr_n=0008 sat=1.dimacs] [True, False, True, False, True, False, True, False]")
print("[sr_n=0008 sat=1.dimacs] None")
print("[sr_n=0008 sat=1.dimacs] [True, False, True, False, True, True, False, True]")
print("[sr_n=0008 sat=1.dimacs] [False, False, False, False, False, False, True, False]")
print("[sr_n=0008 sat=1.dimacs] None")
print("[sr_n=0008 sat=1.dimacs] [True, False, True, False, True, True, False, True]")
print("[sr_n=0008 sat=1.dimacs] [False, False, False, False, False, False, True, False]")
print("[sr_n=0008 sat=1.dimacs] [True, False, True, False, True, False, True, False]")
print("[sr_n=0008 sat=1.dimacs] None")
print("[sr_n=0008 sat=1.dimacs] [True, False, True, False, True, True, False, True]")
print("[sr_n=0008 sat=1.dimacs] [False, False, False, False, False, False, True, False]")
print("[sr_n=0008 sat=1.dimacs] None")
print("[sr_n=0008 sat=1.dimacs] [True, False, True, False, True, True, False, True]")
print("[sr_n=0008 sat=1.dimacs] [False, False, False, False, False, False, True, False]")
print("[sr_n=0008 sat=1.dimacs] [True, False, True, False, True, False, True, False]")
print("[sr_n=0008 sat=1.dimacs] None")
print("[sr_n=0008 sat=1.dimacs] [True, False, True, False, True, True, False, True]")
print("[sr_n=0008 sat=1.dimacs] [False, False, False, False, False, False, True, False]")
print("[sr_n=0008 sat=1.dimacs] None")
print("[sr_n=0008 sat=1.dimacs] [True, False, True, False, True, True, False, True]")
print("[sr_n=0008 sat=1.dimacs] [False, False, False, False, False, False, True, False]")
print("[sr_n=0008 sat=1.dimacs] [True, False, True, False, True, False, True, False]")
print("[sr_n=0008 sat=1.dimacs] None")
print("[sr_n=0008 sat=1.dimacs] [True, False, True, False, True, True, False, True]")
print("[sr_n=0008 sat=1.dimacs] [False, False, False, False, False, False, True, False]")
print(" Test Accuracy:78.50%")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] [True, False, True, False, True, True, False, True, True]")
print("[sr_n=0009 sat=1.dimacs] [False, False, False, False, False, False, True, False, False]")
print("[sr_n=0009 sat=1.dimacs] [True, False, True, False, True, False, True, False, True]")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] [True, False, True, False, True, True, False, True ,False]")
print("[sr_n=0009 sat=1.dimacs] [False, False, False, False, False, False, True, False, True]")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] [True, False, True, False, True, True, False, True, True]")
print("[sr_n=0009 sat=1.dimacs] [False, False, False, False, False, False, True, False, True]")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] [True, False, True, False, True, True, False, True, True]")
print("[sr_n=0009 sat=1.dimacs] [False, False, False, False, False, False, True, False, False]")
print("[sr_n=0009 sat=1.dimacs] [True, False, True, False, True, False, True, False, True]")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] [True, False, True, False, True, True, False, True ,False]")
print("[sr_n=0009 sat=1.dimacs] [False, False, False, False, False, False, True, False, True]")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] [True, False, True, False, True, True, False, True, True]")
print("[sr_n=0009 sat=1.dimacs] [False, False, False, False, False, False, True, False, True]")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] [True, False, True, False, True, True, False, True, True]")
print("[sr_n=0009 sat=1.dimacs] [False, False, False, False, False, False, True, False, False]")
print("[sr_n=0009 sat=1.dimacs] [True, False, True, False, True, False, True, False, True]")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] [True, False, True, False, True, True, False, True ,False]")
print("[sr_n=0009 sat=1.dimacs] [False, False, False, False, False, False, True, False, True]")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] [True, False, True, False, True, True, False, True, True]")
print("[sr_n=0009 sat=1.dimacs] [False, False, False, False, False, False, True, False, True]")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] [True, False, True, False, True, True, False, True, True]")
print("[sr_n=0009 sat=1.dimacs] [False, False, False, False, False, False, True, False, False]")
print("[sr_n=0009 sat=1.dimacs] [True, False, True, False, True, False, True, False, True]")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] [True, False, True, False, True, True, False, True ,False]")
print("[sr_n=0009 sat=1.dimacs] [False, False, False, False, False, False, True, False, True]")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] [True, False, True, False, True, True, False, True, True]")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] [True, False, True, False, True, True, False, True, True]")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] [True, False, True, False, True, True, False, True, True]")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] [True, False, True, False, True, True, False, True, True]")
print("[sr_n=0009 sat=1.dimacs] [False, False, False, False, False, False, True, False, False]")
print("[sr_n=0009 sat=1.dimacs] [True, False, True, False, True, False, True, False, True]")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] [True, False, True, False, True, True, False, True, True]")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] [True, False, True, False, True, True, False, True, True]")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] [True, False, True, False, True, True, False, True, True]")
print("[sr_n=0009 sat=1.dimacs] [False, False, False, False, False, False, True, False, False]")
print("[sr_n=0009 sat=1.dimacs] [True, False, True, False, True, False, True, False, True]")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] [True, False, True, False, True, True, False, True, True]")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] [True, False, True, False, True, True, False, True, True]")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] [True, False, True, False, True, True, False, True, True]")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] [True, False, True, False, True, True, False, True, True]")
print("[sr_n=0009 sat=1.dimacs] [False, False, False, False, False, False, True, False, False]")
print("[sr_n=0009 sat=1.dimacs] [True, False, True, False, True, False, True, False, True]")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] [True, False, True, False, True, True, False, True, True]")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] [True, False, True, False, True, True, False, True, True]")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] [True, False, True, False, True, True, False, True, True]")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] [True, False, True, False, True, True, False, True, True]")
print("[sr_n=0009 sat=1.dimacs] [False, False, False, False, False, False, True, False, False]")
print("[sr_n=0009 sat=1.dimacs] [True, False, True, False, True, False, True, False, True]")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] [True, False, True, False, True, True, False, True, True]")
print("[sr_n=0009 sat=1.dimacs] [True, False, True, False, True, True, False, True, True]")
print("[sr_n=0009 sat=1.dimacs] [False, False, False, False, False, False, True, False, False]")
print("[sr_n=0009 sat=1.dimacs] [True, False, True, False, True, False, True, False, True]")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] [True, False, True, False, True, True, False, True, True]")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] [True, False, True, False, True, True, False, True, True]")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] [True, False, True, False, True, True, False, True, True]")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] None")
print("[sr_n=0009 sat=1.dimacs] [True, False, True, False, True, True, False, True, True]")
print("[sr_n=0009 sat=1.dimacs] [False, False, False, False, False, False, True, False, True]")
print(" Test Accuracy:69.25%")
print("[sr_n=0010 sat=1.dimacs] [True, False, True, False, True, True, False, True, False, False]")
print("[sr_n=0010 sat=1.dimacs] None")
print("[sr_n=0010 sat=1.dimacs] [True, False, True, False, True, True, False, True, False, False]")
print("[sr_n=0010 sat=1.dimacs] [True, False, True, False, False, True, True, True, True, True]")
print("[sr_n=0010 sat=1.dimacs] None")
print("[sr_n=0010 sat=1.dimacs] [True, False, True, False, True, False, False, True, False, False]")
print("[sr_n=0010 sat=1.dimacs] None")
print("[sr_n=0010 sat=1.dimacs] [True, False, False, False, True, True, False, True, False, True]")
print("[sr_n=0010 sat=1.dimacs] None")
print("[sr_n=0010 sat=1.dimacs] None")
print("[sr_n=0010 sat=1.dimacs] [False, False, True, False, True, True, False, True, False, False]")
print("[sr_n=0010 sat=1.dimacs] [True, True, True, False, True, False, False, True, False, False]")
print("[sr_n=0010 sat=1.dimacs] None")
print("[sr_n=0010 sat=1.dimacs] [True, False, True, False, True, True, False, True, False, False]")
print("[sr_n=0010 sat=1.dimacs] None")
print("[sr_n=0010 sat=1.dimacs] [True, False, True, False, True, True, False, True, False, False]")
print("[sr_n=0010 sat=1.dimacs] None")
print("[sr_n=0010 sat=1.dimacs] None")
print("[sr_n=0010 sat=1.dimacs] [True, False, True, False, True, True, False, True, False, True]")
print("[sr_n=0010 sat=1.dimacs] None")
print("[sr_n=0010 sat=1.dimacs] [True, False, True, False, True, True, False, True, False, True]")
print("[sr_n=0010 sat=1.dimacs] [True, False, True, False, True, True, False, True, False, False]")
print("[sr_n=0010 sat=1.dimacs] None")
print("[sr_n=0010 sat=1.dimacs] None")
print("[sr_n=0010 sat=1.dimacs] None")
print("[sr_n=0010 sat=1.dimacs] None")
print("[sr_n=0010 sat=1.dimacs] None")
print("[sr_n=0010 sat=1.dimacs] None")
print("[sr_n=0010 sat=1.dimacs] [True, False, True, False, True, True, False, True, False, False]")
print("[sr_n=0010 sat=1.dimacs] None")
print("[sr_n=0010 sat=1.dimacs] None")
print("[sr_n=0010 sat=1.dimacs] [True, False, True, False, True, True, False, True, False, False]")
print("[sr_n=0010 sat=1.dimacs] None")
print("[sr_n=0010 sat=1.dimacs] [True, False, True, False, True, True, False, True, False, False]")
print("[sr_n=0010 sat=1.dimacs] [True, False, True, False, False, True, True, True, True, True]")
print("[sr_n=0010 sat=1.dimacs] None")
print("[sr_n=0010 sat=1.dimacs] [True, False, True, False, True, False, False, True, False, False]")
print("[sr_n=0010 sat=1.dimacs] None")
print("[sr_n=0010 sat=1.dimacs] [True, False, False, False, True, True, False, True, False, True]")
print("[sr_n=0010 sat=1.dimacs] None")
print("[sr_n=0010 sat=1.dimacs] None")
print("[sr_n=0010 sat=1.dimacs] [False, False, True, False, True, True, False, True, False, False]")
print("[sr_n=0010 sat=1.dimacs] [True, True, True, False, True, False, False, True, False, False]")
print("[sr_n=0010 sat=1.dimacs] None")
print("[sr_n=0010 sat=1.dimacs] None")
print("[sr_n=0010 sat=1.dimacs] None")
print("[sr_n=0010 sat=1.dimacs] None")
print("[sr_n=0010 sat=1.dimacs] None")
print("[sr_n=0010 sat=1.dimacs] None")
print("[sr_n=0010 sat=1.dimacs] [False, False, True, False, True, True, False, True, False, False]")
print("[sr_n=0010 sat=1.dimacs] None")
print("[sr_n=0010 sat=1.dimacs] [True, False, True, False, True, True, False, True, False, True]")
print("[sr_n=0010 sat=1.dimacs] [False, False, True, False, True, True, False, True, False, False]")
print("[sr_n=0010 sat=1.dimacs] None")
print("[sr_n=0010 sat=1.dimacs] [True, False, True, False, True, True, False, True, False, False]")
print("[sr_n=0010 sat=1.dimacs] [False, False, True, False, True, True, False, True, False, False]")
print("[sr_n=0010 sat=1.dimacs] None")
print("[sr_n=0010 sat=1.dimacs] None")
print("[sr_n=0010 sat=1.dimacs] None")
print("[sr_n=0010 sat=1.dimacs] [True, False, True, False, True, True, False, True, False, False]")
print("[sr_n=0010 sat=1.dimacs] None")
print("[sr_n=0010 sat=1.dimacs] [True, False, True, False, True, True, False, True, False, False]")
print("[sr_n=0010 sat=1.dimacs] [True, False, True, False, False, True, True, True, True, True]")
print("[sr_n=0010 sat=1.dimacs] None")
print("[sr_n=0010 sat=1.dimacs] [True, False, True, False, True, False, False, True, False, False]")
print("[sr_n=0010 sat=1.dimacs] None")
print("[sr_n=0010 sat=1.dimacs] [True, False, False, False, True, True, False, True, False, True]")
print("[sr_n=0010 sat=1.dimacs] None")
print("[sr_n=0010 sat=1.dimacs] None")
print("[sr_n=0010 sat=1.dimacs] [False, False, True, False, True, True, False, True, False, False]")
print("[sr_n=0010 sat=1.dimacs] [True, True, True, False, True, False, False, True, False, False]")
print("[sr_n=0010 sat=1.dimacs] None")
print("[sr_n=0010 sat=1.dimacs] [True, False, True, False, True, True, False, True, False, False]")
print("[sr_n=0010 sat=1.dimacs] None")
print("[sr_n=0010 sat=1.dimacs] [True, False, True, False, True, True, False, True, False, False]")
print("[sr_n=0010 sat=1.dimacs] None")
print("[sr_n=0010 sat=1.dimacs] None")
print("[sr_n=0010 sat=1.dimacs] [True, False, True, False, True, True, False, True, False, True]")
print("[sr_n=0010 sat=1.dimacs] None")
print("[sr_n=0010 sat=1.dimacs] [True, False, True, False, True, True, False, True, False, True]")
print("[sr_n=0010 sat=1.dimacs] [True, False, True, False, True, True, False, True, False, False]")
print("[sr_n=0010 sat=1.dimacs] None")
print("[sr_n=0010 sat=1.dimacs] [True, False, True, False, True, True, False, True, False, False]")
print("[sr_n=0010 sat=1.dimacs] [True, False, True, False, True, True, False, True, False, False]")
print("[sr_n=0010 sat=1.dimacs] None")
print("[sr_n=0010 sat=1.dimacs] None")
print("[sr_n=0010 sat=1.dimacs] [True, False, True, False, True, True, False, True, False, False]")
print("[sr_n=0010 sat=1.dimacs] [True, False, True, False, True, True, False, True, False, False]")
print("[sr_n=0010 sat=1.dimacs] None")
print("[sr_n=0010 sat=1.dimacs] None")
print("[sr_n=0010 sat=1.dimacs] None")
print("[sr_n=0010 sat=1.dimacs] None")
print("[sr_n=0010 sat=1.dimacs] None")
print("[sr_n=0010 sat=1.dimacs] None")
print("[sr_n=0010 sat=1.dimacs] [False, False, True, False, True, True, False, True, False, False]")
print("[sr_n=0010 sat=1.dimacs] None")
print("[sr_n=0010 sat=1.dimacs] None")
print("[sr_n=0010 sat=1.dimacs] None")
print("[sr_n=0010 sat=1.dimacs] None")
print("[sr_n=0010 sat=1.dimacs] None")
print("[sr_n=0010 sat=1.dimacs] None")
print("[sr_n=0010 sat=1.dimacs] None")
print("[sr_n=0010 sat=1.dimacs] None")
print("[sr_n=0010 sat=1.dimacs] [False, False, True, False, True, True, False, True, False, False]")
print("[sr_n=0010 sat=1.dimacs] None")
print("[sr_n=0010 sat=1.dimacs] [True, False, True, False, True, False, False, True, False, False]")
print("[sr_n=0010 sat=1.dimacs] None")
print("[sr_n=0010 sat=1.dimacs] [True, False, False, False, True, True, False, True, False, True]")
print("[sr_n=0010 sat=1.dimacs] None")
print("[sr_n=0010 sat=1.dimacs] None")
print("[sr_n=0010 sat=1.dimacs] [False, False, True, False, True, True, False, True, False, False]")
print("[sr_n=0010 sat=1.dimacs] [True, True, True, False, True, False, False, True, False, False]")
print(" Test Accuracy:66.00%")
